
include:
  - keys.yaml

# The music library directory  
directory: /stuff/media/music
library: /stuff/media/music/beets.db

plugins:
  - inline
  - fetchart
  - lyrics
  - lastgenre
  - embedart
  - autobpm
  - info
  - badfiles
  - mbsync
  
  # Data sources
  - chroma # Acoustic fingerprinting
  - musicbrainz
  - spotify
  # - deezer

# Data source preferences
# data_source_mismatch_penalty dictates which sources to prefer (default penalty is 0.5, smaller=preferred)
musicbrainz:
  data_source_mismatch_penalty: 0.0
  extra_tags: [barcode, catalognum, country, label, media, year]
  external_ids:
    bandcamp: yes
    beatport: yes
    deezer: yes
    discogs: yes
    spotify: yes
    tidal: yes

spotify:
  data_source_mismatch_penalty: 0.9

# deezer:
#   data_source_mismatch_penalty: 0.8

# Indicating whether the autotagger should use multiple threads.
threaded: yes

ui:
  color: yes

import:
  write: yes
  copy: yes
  move: yes
  autotag: yes
  resume: ask
  from_scratch: no
  duplicate_action: ask
  bell: yes
  languages: en
  incremental: no
  group_albums: yes
  
match:
  distance_weights:
    # Allow missing tracks from albums
    missing_tracks: 0.2
    # Make unmatched tracks way more important
    unmatched_tracks: 1.0
    

item_fields:
  is_single: 1 if disctotal <= 1 and tracktotal <= 1 else 0
  main_album_artist: albumartists[0] if len(albumartists) >= 1 else albumartist
  main_artist: artists[0] if len(artists) >= 1 else artist
  has_featuring_artists: 1 if len(artists) > 1 else 0
  featuring_artists: "\"\".join(artists[1:]) if len(artists[1:]) <= 1 else \", \".join(artists[1:-1]) + \" & \" + artists[-1]"

# Directory and naming scheme.
paths:
  default: artists/$main_album_artist/%if{$is_single,$artist - $title,$album ($year)/%if{$has_featuring_artists,$track. $title (feat. $featuring_artists),$track. $title}}
  singleton: artists/$main_artist/%if{$is_single,$artist - $title,$album ($year)/%if{$has_featuring_artists,$track. $title (feat. $featuring_artists),$track. $title}}
  albumtype:single: artists/$main_album_artist/%if{$is_single,$artist - $title,$album ($year)/%if{$has_featuring_artists,$track. $title (feat. $featuring_artists),$track. $title}}
  albumtypes:single: artists/$main_album_artist/%if{$is_single,$artist - $title,$album ($year)/%if{$has_featuring_artists,$track. $title (feat. $featuring_artists),$track. $title}}
  albumtype:live: live/$albumartist - $album ($year)/$track. $title
  albumtypes:live: live/$albumartist - $album ($year)/$track. $title
  albumtype:soundtrack: soundtracks/$album ($year)/$track. $title
  albumtypes:soundtrack: soundtracks/$album ($year)/$track. $title
  comp: compilations/$album ($year)/$track. $artist - $title
  
# When beets imports all the files in a directory, it tries to remove the directory if it’s empty.
# A directory is considered empty if it only contains files whose names match the glob patterns in clutter,
# which should be a list of strings.
# The importer only removes recursively searched subdirectories—the top-level directory you specify on the command line is never deleted.
clutter:
  [
    # Defaults
    ".DS_Store", "Thumbs.DB",
    # Extras
    "*.xml", "*.nfo", "*.lrc", "*.jpg", "*.png", ".txt", ".cue"
  ]

# Convert all non-ASCII characters in paths to ASCII equivalents.
# asciify_path: yes

# Make all sequences dissapear instead of adding an underscore, and allow : and ? (which are dissallowed in the default)
replace:
  '[\\/]': ''
  '^\.': ''
  '[\x00-\x1f]': ''
  '[<>"\*\|]': ''
  '\.$': ''
  '\s+$': ''
  '^\s+': ''
  '^-': ''
path_sep_replace: ''

chroma:
  auto: yes

lastgenre:
  auto: yes
  force: no
  keep_existing: no
  whitelist: yes
  count: 5
  source: track
  canonical: yes
  
lyrics:
  auto: yes
  force: no
  print: no
  sources: [lrclib, genius]
  synced: yes

fetchart:
  auto: yes
  high_resolution: yes
  minwidth: 1000
  
embedart:
  auto: yes
  ifempty: no
  maxwidth: 2000
  quality: 90
  remove_art_file: yes

autobpm:
  auto: yes

badfiles:
  check_on_import: yes
  commands:
    flac: flac --test --silent
