

# The music library directory  
directory: /stuff/media/music
library: /stuff/media/music/beets.db

plugins: fetchart lyrics lastgenre embedart inline autobpm info badfiles ftintitle deezer spotify

# Which sources to prefer (default penalty is 0.5, smaller=preferred)
deezer:
  data_source_mismatch_penalty: 0.6
spotify:
  data_source_mismatch_penalty: 0.7

# Indicating whether the autotagger should use multiple threads.
threaded: yes

ui:
  color: yes

import:
  write: yes
  copy: yes
  # move: yes
  autotag: yes
  resume: ask
  from_scratch: no
  duplicate_action: ask
  bell: yes
  languages: en
  incremental: no
  
match:
  distance_weights:
    # Allow missing tracks from albums
    missing_tracks: 0.2
    # Make unmatched tracks way more important
    unmatched_tracks: 1.0
    
item_fields:
  is_single: 1 if disctotal <= 1 and tracktotal <= 1 else 0
  main_album_artist: |
    import re
    return re.split('\s+(feat(.?|uring)|ft\.?)', albumartist, 1, flags=re.IGNORECASE)[0]
  main_artist: |
    import re
    return re.split('\s+(feat(.?|uring)|ft\.?)', artist, 1, flags=re.IGNORECASE)[0]

# Directory and naming scheme.
# The aunique{} function ensures that identically-named albums are placed in different directories.
paths:
  default: artists/$main_album_artist/%if{$is_single,$artist - $title,$album ($year)/$track. $title}
  singleton: artists/$main_artist/%if{$is_single,$artist - $title,$album ($year)/$track. $title}
  albumtype:soundtrack: soundtracks/$album ($year)/$track. $title
  comp: compilations/$album ($year)/$track. $artist - $title
  
# When beets imports all the files in a directory, it tries to remove the directory if it’s empty.
# A directory is considered empty if it only contains files whose names match the glob patterns in clutter,
# which should be a list of strings.
# The importer only removes recursively searched subdirectories—the top-level directory you specify on the command line is never deleted.
clutter:
  [
    # Defaults
    ".DS_Store", "Thumbs.DB",
    # Extras
    "*.xml", "*.nfo", "*.lrc", "*.jpg", "*.png", ".txt", ".cue"
  ]

# Convert all non-ASCII characters in paths to ASCII equivalents.
# asciify_path: yes

# Make all sequences dissapear instead of adding an underscore, and allow : and ? (which are dissallowed in the default)
replace:
  '[\\/]': ''
  '^\.': ''
  '[\x00-\x1f]': ''
  '[<>"\*\|]': ''
  '\.$': ''
  '\s+$': ''
  '^\s+': ''
  '^-': ''
path_sep_replace: ''


lastgenre:
  auto: yes
  force: yes
  keep_existing: no
  whitelist: yes
  count: 5
  
lyrics:
  auto: yes
  force: no
  print: no
  sources: [lrclib, genius]
  synced: yes
  
fetchart:
  auto: yes
  high_resolution: yes
  
embedart:
  auto: yes
  remove_art_file: yes
  ifempty: no

autobpm:
  auto: yes

badfiles:
  check_on_import: yes
  commands:
      flac: flac --test --silent

ftintitle:
  auto: yes
  format: (feat. {0})
